# Generated by Django 5.1 on 2024-08-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('style', models.CharField(max_length=50)),
                ('size_sqft', models.PositiveIntegerField()),
                ('num_bedrooms', models.PositiveIntegerField()),
                ('num_bathrooms', models.PositiveIntegerField()),
                ('additional_rooms', models.TextField(blank=True, null=True)),
                ('layout', models.CharField(max_length=50)),
                ('exterior_materials', models.CharField(max_length=255)),
                ('roofing', models.CharField(max_length=255)),
                ('windows', models.CharField(max_length=255)),
                ('doors', models.CharField(max_length=255)),
                ('landscaping', models.TextField(blank=True, null=True)),
                ('flooring', models.CharField(max_length=255)),
                ('wall_finishes', models.CharField(max_length=255)),
                ('kitchen_details', models.TextField(blank=True, null=True)),
                ('bathrooms_details', models.TextField(blank=True, null=True)),
                ('lighting', models.CharField(max_length=255)),
                ('heating_cooling', models.CharField(max_length=255)),
                ('plumbing', models.TextField(blank=True, null=True)),
                ('electrical', models.TextField(blank=True, null=True)),
                ('smart_home_features', models.TextField(blank=True, null=True)),
                ('local_building_codes', models.TextField(blank=True, null=True)),
                ('permits_required', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('accessibility_features', models.TextField(blank=True, null=True)),
                ('eco_friendly_options', models.TextField(blank=True, null=True)),
                ('custom_features', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('contract_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Home Project',
                'verbose_name_plural': 'Home Projects',
            },
        ),
    ]
