# Generated by Django 5.1 on 2024-08-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeproject', '0002_alter_homeproject_options_homeproject_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeproject',
            name='accessibility_features',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='additional_rooms',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='bathrooms_details',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='contract_details',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='custom_features',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='eco_friendly_options',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='electrical',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='exterior_materials',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='flooring',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='heating_cooling',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='kitchen_details',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='landscaping',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='lighting',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='local_building_codes',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='permits_required',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='plumbing',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='roofing',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='smart_home_features',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='wall_finishes',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='windows',
        ),
    ]
