# Generated by Django 5.1 on 2024-08-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeproject', '0003_remove_homeproject_accessibility_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='sample_design',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
    ]
