# Generated by Django 5.1 on 2024-08-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeproject', '0004_homeproject_sample_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='date_of_registration',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
