# Generated by Django 5.1 on 2024-08-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeproject', '0005_homeproject_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='company_budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homeproject',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in-review', 'in-review'), ('accepted', 'accepted'), ('declined', 'declined'), ('negotiable', 'negotiable')], default='pending', max_length=100, null=True),
        ),
    ]
