# Generated by Django 5.1 on 2024-08-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeproject', '0007_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='project',
            new_name='project_name',
        ),
    ]
