# Generated by Django 5.1 on 2024-08-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeproject', '0009_call_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='requested_call',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
