# Generated by Django 5.1 on 2024-08-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpmod',
            name='keywords',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
