# Generated by Django 5.1 on 2024-08-14 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Handyman', 'Handyman'), ('HVAC Technician', 'HVAC Technician'), ('Painter', 'Painter'), ('Appliance Repair Technician', 'Appliance Repair Technician'), ('General Contractor', 'General Contractor'), ('Gardener', 'Gardener'), ('Landscaper', 'Landscaper'), ('Tree Surgeon', 'Tree Surgeon'), ('Pest Control Specialist', 'Pest Control Specialist'), ('Pool Maintenance Technician', 'Pool Maintenance Technician'), ('Window Cleaner', 'Window Cleaner'), ('Pressure Washer Technician', 'Pressure Washer Technician'), ('House Cleaner', 'House Cleaner'), ('Carpet Cleaner', 'Carpet Cleaner'), ('Chimney Sweep', 'Chimney Sweep'), ('Gutter Cleaner', 'Gutter Cleaner'), ('Home Security Installer', 'Home Security Installer'), ('Locksmith', 'Locksmith'), ('Fire Safety Technician', 'Fire Safety Technician'), ('Interior Designer', 'Interior Designer'), ('Professional Organizer', 'Professional Organizer'), ('Home Stager', 'Home Stager'), ('Smart Home Installer', 'Smart Home Installer'), ('Roofer', 'Roofer'), ('Tiler', 'Tiler'), ('Flooring Installer', 'Flooring Installer'), ('Drywall Installer', 'Drywall Installer'), ('Plasterer', 'Plasterer'), ('Mason', 'Mason'), ('Welder', 'Welder'), ('Fence Installer', 'Fence Installer'), ('Solar Panel Installer', 'Solar Panel Installer'), ('Garage Door Technician', 'Garage Door Technician'), ('Customer Service Representative', 'Customer Service Representative'), ('Scheduler', 'Scheduler'), ('Quality Control Inspector', 'Quality Control Inspector'), ('Office Manager', 'Office Manager')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='workers/')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('member_since', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.role')),
            ],
        ),
    ]
