# Generated by Django 5.1 on 2024-08-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
