# Generated by Django 5.1 on 2024-08-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_workers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='role',
        ),
        migrations.AlterField(
            model_name='workers',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.role'),
        ),
    ]
