# Generated by Django 5.1 on 2024-08-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_remove_purchase_role_alter_workers_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(blank=True, choices=[('arrived', 'arrived'), ('delay', 'delay'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('rejected', 'rejected'), ('on the way', 'on the way')], max_length=200, null=True),
        ),
    ]
