# Generated by Django 5.1 on 2024-08-17 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_purchase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date_scheduled',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_cancel', models.CharField(max_length=600)),
                ('reason', models.CharField(choices=[('i have found better deal somewhere', 'i have found better deal somewhere'), ('too expensive', 'too expensive')], max_length=400)),
                ('rating', models.IntegerField(default=1)),
                ('date_Cancelled', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workers')),
            ],
        ),
    ]
