# Generated by Django 5.1 on 2024-08-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
