# Generated by Django 5.1 on 2024-08-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='is_premium',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
