# Generated by Django 5.1 on 2024-08-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0021_alter_discounts_content_alter_discounts_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounts',
            name='link',
        ),
    ]
