# Generated by Django 5.1 on 2024-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0022_remove_discounts_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='discount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
